version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1999King
      POSTGRES_DB: delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile  

    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Database=delivery;Username=postgres;Password=1999King"

 # driver-service:
 #   build: ./driver-service
 #   ports:
 #     - "8080:8080"
 #   depends_on:
 #     - postgres

volumes:
  postgres-data: